Add script to ensure travis is not changed
githubteacher/practice-sinatra pull request #2
Opened 2017-01-10 19:33 UTC by brianamarie

This PR starts to add changes for a script that will serve as an additional layer of security for the [on demand repos](). Travis is enabled with protected branches, but if a user changes the travis code, they can get past this. 

This PR adds a script that will use webhooks on push events and the API to send the status based on the contents of the travis file.

cc/ @swinton @crichID @hectorsector @hollenberry @beardofedu

2017-01-13 03:52 UTC, hectorsector commented
@brianamarie how can I help you test this?

2017-01-13 10:14 UTC, stoe requested changes

2017-01-13 10:14 UTC, stoe commented on check-for-travis.rb
> +client = Octokit::Client.new :netrc => true
@brianamarie, we shouldn't be using `.netrc` at all here.

2017-01-13 10:14 UTC, stoe commented on check-for-travis.rb
> +client = Octokit::Client.new :netrc => true
better to use

```rb
client = Octokit::Client.new :access_token => ENV['GITHUBTEACHER_TOKEN'] || raise("You need a GitHub Teacher access token")
```

`ENV['GITHUBTEACHER_TOKEN']` is available on the heroku instance this is running on, e.g. https://github.com/githubteacher/practice-sinatra/blob/master/collaborators.rb#L61.

2017-01-13 10:14 UTC, stoe commented on check-for-travis.rb
> +# Send status back via API
maybe

```rb
// TODO: we need the current commit's `sha`

client.create_status("githubschool/on-demand-github-pages", sha, "failure", {
  :description => "You are not allowed to change .travis.yml"
})
```

https://octokit.github.io/octokit.rb/Octokit/Client/Statuses.html#create_status-instance_method

2017-01-13 13:58 UTC, brianamarie commented
@stoe Thank you for the 👀 and review. I put your suggestions in. 

@hectorsector I don't believe it's ready to test yet. I think it needs a little more work, now described in the 'TODO' section.

2017-01-13 15:05 UTC, githubteacher commented
You are not allowed to change `.travis.yml`, please reveret your changes to `.travis.yml` and commit again.

2017-01-13 15:08 UTC, githubteacher commented
You are not allowed to change `.travis.yml`, please reveret your changes to `.travis.yml` and commit again.

2017-01-13 15:15 UTC, swinton commented on check-for-travis.rb
> +tree = client.tree("githubschool/on-demand-github-pages", "f1b10e926e7ace9862bf65b789204f22cccba1e0")
The sha, `f1b10e926e7ace9862bf65b789204f22cccba1e0`, shouldn't be hard coded, we should use the sha that's submitted to us via the webhook.

2017-01-13 15:16 UTC, swinton commented on check-for-travis.rb
> +puts Base64.decode64(blob.content)
Instead of using `puts`, we need to verify the `blog.content` somehow, I'd suggest hashing the content and comparing it to a known hash.

2017-01-13 15:18 UTC, swinton commented on check-for-travis.rb
> +travis_yml = tree.tree.select { |t| t.path == ".travis.yml" }
I think we need to verify other files besides `.travis.yml`, e.g. [the other test scripts in the repo](https://github.com/githubschool/on-demand-github-pages/tree/master/tests)?

2017-01-13 15:19 UTC, stoe commented on check-for-travis.rb
> +puts Base64.decode64(blob.content)
Been working on that.

```rb
#!/usr/bin/env ruby
require 'octokit'
require 'digest'

client = Octokit::Client.new :access_token => ENV['GITHUBTEACHER_TOKEN'] || raise("You need a GitHub Teacher access token")

# Get the tree for a sha
tree = client.tree("githubschool/on-demand-github-pages", "7e88ef3d11f84ed351bf1e0d733fef7cbe54fc18")

# Select .travis.yml from the tree
travis_yml = tree.tree.select { |t| t.path == ".travis.yml" }

puts travis_yml.inspect

# Get the corresponding blob for the .travis.yml sha
blob = client.blob("githubschool/on-demand-github-pages", travis_yml.first.sha)

travis_yml_sha256 = Digest::SHA256.new
travis_yml_sha256.update Base64.decode64(blob.content)

# TODO: find commit's .travis.yml content and `sha` to compare to `travis_yml_sha256`

current_cimmit_sha = "bb8c9e186f687ca3af294dbb2bf870040e837766" # TODO: we need the current commit's `sha`
current_pr_id = 2                                               ## TODO: we need the current commit's `id`

if current_cimmit_sha != travis_yml_sha256.hexdigest
  # client.create_status "githubteacher/practice-sinatra", current_cimmit_sha, "failure", :description => "You are not allowed to change `.travis.yml`, please reveret your changes to `.travis.yml` and commit again."
  #
  # client.add_comment "githubteacher/practice-sinatra", current_pr_id, "You are not allowed to change `.travis.yml`, please reveret your changes to `.travis.yml` and commit again."

  puts ".travis.yml changed !!"
end
```

Something like that maybe.
We need 
- the commit `sha`
- the committed `.travis.yml` content to SHA256 for comparison
- the original `.travis.yml` content we want to set as ungangeable
- the original `.travis.yml` SHA256 for comparison

2017-01-13 15:20 UTC, swinton commented
We also need to modify [this function in `basics.rb`](https://github.com/githubteacher/practice-sinatra/blob/7d3c968c2408cc90211574d55ab25381345f8ed1/basics.rb#L8), so it can handle different webhooks, and route them to the relevant _handlers_.

2017-01-13 15:20 UTC, stoe commented on check-for-travis.rb
> +puts Base64.decode64(blob.content)
the if part I tested, that's why the two @githubteacher comments and the "failure" status.

2017-01-13 15:21 UTC, stoe commented
> We also need to modify this function in basics.rb, so it can handle different webhooks, and route them to the relevant handlers.

Or we set the "blockers" to run first and only if successful run the rest.

2017-05-26 19:44 UTC, brianamarie commented
@hectorsector Do you think this type of functionality would be transferrable to teacherbot? I think it may almost be set up in the same way.

2017-05-31 19:05 UTC, hectorsector commented
Sounds like it could, @brianamarie! Let's begin opening issues for teacherbot functionality directly on https://github.com/github/teacher-bot

2017-05-31 19:19 UTC, brianamarie commented
> Sounds like it could, @brianamarie! Let's begin opening issues for teacherbot functionality directly on https://github.com/github/teacher-bot

Fabulous idea, @hectorsector. [PR opened](https://github.com/github/teacher-bot/issues/10). I am going to close this issue out since it is being addressed in another way. 🎉

2017-05-31 19:19 UTC, closed without merging